// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnycS6g_tOhXGGvf-sjsHcKPBApWsGWqw',
    appId: '1:388617338948:web:e1dd0e0b75d55f6c01bc11',
    messagingSenderId: '388617338948',
    projectId: 'balder-27351',
    authDomain: 'balder-27351.firebaseapp.com',
    storageBucket: 'balder-27351.appspot.com',
    measurementId: 'G-RCP51J440L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-qwRrihl6LGF6AS2nvjwS-XxRbgwibh8',
    appId: '1:388617338948:android:8effb490d05178f301bc11',
    messagingSenderId: '388617338948',
    projectId: 'balder-27351',
    storageBucket: 'balder-27351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX2TwePQ8vVRPjF07dSt3LDnO4lfm5GX8',
    appId: '1:388617338948:ios:e844fb4d977f600401bc11',
    messagingSenderId: '388617338948',
    projectId: 'balder-27351',
    storageBucket: 'balder-27351.appspot.com',
    iosClientId: '388617338948-h0q2klu2mk268reqnacbqslqk1d3qilr.apps.googleusercontent.com',
    iosBundleId: 'fr.ferryl.baldrapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX2TwePQ8vVRPjF07dSt3LDnO4lfm5GX8',
    appId: '1:388617338948:ios:e844fb4d977f600401bc11',
    messagingSenderId: '388617338948',
    projectId: 'balder-27351',
    storageBucket: 'balder-27351.appspot.com',
    iosClientId: '388617338948-h0q2klu2mk268reqnacbqslqk1d3qilr.apps.googleusercontent.com',
    iosBundleId: 'fr.ferryl.baldrapp',
  );
}
